name: Flutter Web Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Clean previous build
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        # Sửa lại để khớp với thư mục static trong dự án Django của bạn
        run: flutter build web --release --base-href="/static/heartbeat_app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          force_orphan: true